### ISSUE TITLE
Feature request: allow gradient background

### ISSUE THREAD

**Issue by juanitotc** [swaywm/swaybg#80]
Is it possible to add the ability to specify a gradient backgound in a similar fashion to this:

`hsetroot -add "#0E5CA8" -add "#87C6C9" -gradient 0`

**Comment by emersion** [comment]
No, this is not supported, and I don't think we'd want to add the complexity. Alternatively:

- You can use an SVG file.
- You can ask for this feature on one of the swaybg alternatives.

**Comment by mstoeckl** [comment]
> You can use an SVG file.

I recommend this option. Gradients can be made with a very simple SVG file, although (due to https://github.com/swaywm/swaybg/issues/60) you need to explicitly set width/height to the screen dimensions. In the following example, if you had a `1600x1200` display, you'd need to replace `width="100%" height="100%"` with  `width="1600" height="1200"`, 
```svg
<svg width="100%" height="100%" version="1.1" xmlns="http://www.w3.org/2000/svg">
<defs>
<linearGradient id="gradient" gradientTransform="rotate(45)">
<stop offset="0%" stop-color="#0E5CA8" />
<stop offset="100%" stop-color="#87C6C9" />
</linearGradient>
</defs>
<rect width="100%" height="100%" fill="url('#gradient')"/>
</svg>
```
